name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Set the Token
      run: |
       git config user.email "raj.vasupilli@gmail.com"
       git config user.name "rajvasupilli"
       export GITHUB_TOKEN=999d7b9608fff6f7dda2d4729d021378918b892a
       env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
    
    - name: Run tests
      run: sbt test
    
    - name: test
      run: git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
    
    - name: Publish a package
      run: sbt publish
      env:
        GITHUB_TOKEN: $GITHUB_TOKEN
